import test from 'node:test';
import assert from 'node:assert/strict';
import {createRooms,evaluateRoom,priorityRooms,summarize,changeSensor,applyScenario} from '../dist/model.js';
test('vacant, open door and AC triggers after five minutes; acknowledgement does not resolve',()=>{const r=createRooms().find(r=>r.id==='203');assert.equal(evaluateRoom({...r,minutes:4}).type,'observing');assert.equal(evaluateRoom({...r,minutes:5}).level,'critical');assert.equal(evaluateRoom({...r,acknowledged:true}).level,'critical');assert.equal(evaluateRoom(r).estimateKWh,.504);});
test('unknown occupancy is not treated as an empty classroom',()=>{const r=createRooms().find(r=>r.id==='203');assert.equal(evaluateRoom({...r,occupied:'unknown',door:false}).level,'normal');assert.equal(evaluateRoom({...r,occupied:'unknown'}).type,'open-door');});
test('stale data takes precedence and is excluded from energy totals',()=>{const rooms=createRooms();const before=summarize(rooms);const r=rooms.find(r=>r.id==='203');r.stale=true;assert.equal(evaluateRoom(r).type,'stale');assert.equal(evaluateRoom(r).estimateKWh,null);assert.equal(summarize(rooms).unknown,1);assert.ok(Math.abs(summarize(rooms).powerKW-(before.powerKW-1.92))<1e-8);});
test('closing door keeps vacant cooling condition for new observation period',()=>{const r=createRooms().find(r=>r.id==='203');const closed=changeSensor(r,'door',false);assert.equal(evaluateRoom(closed).type,'observing');assert.equal(evaluateRoom(changeSensor(closed,'minutes',5)).type,'vacant-ac');const off=changeSensor(closed,'ac',false);assert.equal(off.powerW,240);assert.equal(evaluateRoom(off).level,'normal');});
test('scenarios and counts agree',()=>{assert.equal(priorityRooms(createRooms()).length,3);assert.equal(priorityRooms(applyScenario('normal')).length,0);assert.equal(summarize(applyScenario('after-school')).critical,11);assert.equal(summarize(applyScenario('sensor-loss')).unknown,1);});
test('sensor API rejects invalid values without changing original record',()=>{const r=createRooms()[0];assert.throws(()=>changeSensor(r,'minutes',-1));assert.throws(()=>changeSensor(r,'occupied','empty'));assert.throws(()=>changeSensor(r,'ac','false'));assert.throws(()=>applyScenario('invalid'));assert.equal(r.ac,true);});
